# Serena Project Configuration for wvwo-storefront
# Rich documentation moved to Serena memory: wvwo-project-context.md

# Languages (auto-detected, but explicit for TypeScript/Astro project)
languages:
  - typescript
  - javascript

# Paths to ignore
ignored_paths:
  - node_modules
  - dist
  - .astro
  - .git
  - coverage
  - playwright-report
  - .swarm

# Tools to disable for this project
excluded_tools: []

# Optional tools to enable
included_optional_tools: []

# Prevent file modifications
read_only: false

# Respect .gitignore patterns
ignore_all_files_in_gitignore: true

# Project context for Serena
initial_prompt: |
  WVWO Storefront - West Virginia Wild Outdoors adventure destination hub.
  Stack: Astro 5, TypeScript, Tailwind 4, React, shadcn/ui.
  Design: ONLY rounded-sm, brand colors only, Kim's authentic rural WV voice.
  See memory file 'wvwo-project-context.md' for full design system and guidelines.

# Source encoding
encoding: utf-8
